default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.4
    hooks:
      - id: remove-crlf
      - id: remove-tabs
        args: [ --whitespaces-count=2 ]
  - repo: https://github.com/extenda/pre-commit-hooks
    rev: v0.4
    hooks:
      - id: google-java-formatter
      - id: commitlint
        stages: [commit-msg]
